# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e67c44078ebe713b8657c5377691880a94ceb708516c18a511bcfbc49ab576a7a0635d2583503b6a333afc55e4fb05e05359016696ccd3776a77de20f6ecab4

test:
  secret_key_base: 1858b686c5765d708b38ecbada66c4d4007b7e5422ac00dc4ad314bb99892f3dd9b65599f0ce0d7507a883b5f1b48e93778f4a1ea16b4c9627ec4c8b39ebb0eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
